@startuml

Interface Promotion {
    getDiscountAmount()
}

Class Product implements Promotion{
    String name
    int price
    int weight
    int delivery

    getDiscountAmount()
}

Class Cart {
    Product[] products
    calculateDeliveryCharge()
}

Class Grocery extends Product{
}

Class Beauty extends Product{
}

Class LargeAppliance extends Product{
}

@enduml